/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mu_pet_coba;
import java.sql.*;
import javax.swing.*;
import java.awt.*;
/**
 *
 * @author resky
 */
public class menu extends javax.swing.JFrame {
    public static int x,y;
    
    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
        setLocation(500, 200);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_reservasi = new javax.swing.JLabel();
        btn_bayar = new javax.swing.JLabel();
        btn_karyawan = new javax.swing.JLabel();
        btn_masterdata = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btn_registrasi = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_close = new javax.swing.JLabel();
        mouse_moved = new javax.swing.JLabel();
        lbl_stst = new javax.swing.JLabel();
        lbl_id = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_reservasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menustuff/reservasi.png"))); // NOI18N
        btn_reservasi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_reservasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_reservasiMouseClicked(evt);
            }
        });
        getContentPane().add(btn_reservasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 90, 110));

        btn_bayar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menustuff/pembayaran.png"))); // NOI18N
        btn_bayar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_bayar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_bayarMouseClicked(evt);
            }
        });
        getContentPane().add(btn_bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, 120, 70));

        btn_karyawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menustuff/registrasi.png"))); // NOI18N
        btn_karyawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_karyawanMouseClicked(evt);
            }
        });
        getContentPane().add(btn_karyawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 290, 90, 100));

        btn_masterdata.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menustuff/master_data.png"))); // NOI18N
        btn_masterdata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_masterdataMouseClicked(evt);
            }
        });
        getContentPane().add(btn_masterdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 290, 90, 90));

        jLabel6.setFont(new java.awt.Font("Helvetica", 1, 16)); // NOI18N
        jLabel6.setText("Reservasi");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, -1, -1));

        jLabel7.setFont(new java.awt.Font("Helvetica", 1, 16)); // NOI18N
        jLabel7.setText("Pembayaran");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 440, -1, -1));

        jLabel8.setFont(new java.awt.Font("Helvetica", 1, 16)); // NOI18N
        jLabel8.setText("Tambah Karyawan");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 440, -1, -1));

        jLabel9.setFont(new java.awt.Font("Helvetica", 1, 16)); // NOI18N
        jLabel9.setText("Master Data");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 440, -1, -1));

        btn_registrasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menustuff/regis_pelanggan.png"))); // NOI18N
        btn_registrasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_registrasiMouseClicked(evt);
            }
        });
        getContentPane().add(btn_registrasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 100, 100));

        jLabel3.setFont(new java.awt.Font("Helvetica", 1, 16)); // NOI18N
        jLabel3.setText("Registrasi");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, -1, -1));

        btn_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/banner/close.png"))); // NOI18N
        btn_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_closeMouseClicked(evt);
            }
        });
        getContentPane().add(btn_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 10, -1, -1));

        mouse_moved.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                mouse_movedMouseDragged(evt);
            }
        });
        mouse_moved.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mouse_movedMousePressed(evt);
            }
        });
        getContentPane().add(mouse_moved, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 80));

        lbl_stst.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        lbl_stst.setText("jLabel2");
        getContentPane().add(lbl_stst, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 600, -1, 20));

        lbl_id.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lbl_id.setText("jLabel4");
        getContentPane().add(lbl_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 630, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/banner/profile.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, -1, -1));

        jLabel1.setFont(new java.awt.Font("Helvetica", 1, 16)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menustuff/Menu.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1100, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_reservasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_reservasiMouseClicked
        // TODO add your handling code here:
        reservasi reser = new reservasi();
        reser.setVisible(true);
        reser.txt_idkar.setText(lbl_id.getText());
        
    }//GEN-LAST:event_btn_reservasiMouseClicked

    private void btn_bayarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_bayarMouseClicked
        // TODO add your handling code here:
        pembayaran bayar = new pembayaran();
        bayar.setVisible(true);
        bayar.txt_idkar.setText(lbl_id.getText());
    }//GEN-LAST:event_btn_bayarMouseClicked

    private void btn_karyawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_karyawanMouseClicked
        // TODO add your handling code here:
        add_karyawan karyawan = new add_karyawan();
        karyawan.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_karyawanMouseClicked

    private void btn_masterdataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_masterdataMouseClicked
        // TODO add your handling code here:
        master_men masterx = new master_men();
        masterx.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_masterdataMouseClicked

    private void btn_registrasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registrasiMouseClicked
        // TODO add your handling code here:
        regs_menu menu2 = new regs_menu();
        menu2.setVisible(true);
        menu2.lbl_status.setText(lbl_stst.getText());
        menu2.label_apaan.setText(lbl_id.getText());
    }//GEN-LAST:event_btn_registrasiMouseClicked

    private void btn_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseClicked
        dispose();
    }//GEN-LAST:event_btn_closeMouseClicked

    private void mouse_movedMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouse_movedMouseDragged
        // TODO add your handling code here:
        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        this.setLocation(xx-x, yy-y);
    }//GEN-LAST:event_mouse_movedMouseDragged

    private void mouse_movedMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouse_movedMousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_mouse_movedMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_bayar;
    private javax.swing.JLabel btn_close;
    private javax.swing.JLabel btn_karyawan;
    private javax.swing.JLabel btn_masterdata;
    private javax.swing.JLabel btn_registrasi;
    private javax.swing.JLabel btn_reservasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JLabel lbl_id;
    public static javax.swing.JLabel lbl_stst;
    private javax.swing.JLabel mouse_moved;
    // End of variables declaration//GEN-END:variables
}
