/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mu_pet_coba;
import java.sql.*;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
/**
 *
 * @author resky
 */
public class regs_menu extends javax.swing.JFrame {
    int x,y;
    Connection conn = new koneksi_db().koneksi();
    Statement stat;
    ResultSet res;

    /**
     * Creates new form regs_menu
     */
    public regs_menu() {
        initComponents();
        setLocation(600, 200);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        btn_close = new javax.swing.JLabel();
        mouse_area = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbl_status = new javax.swing.JLabel();
        label_apaan = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn_registrasi = new javax.swing.JLabel();
        btn_koceng = new javax.swing.JLabel();
        btn_reservasi = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_bayar = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/banner/close.png"))); // NOI18N
        btn_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_closeMouseClicked(evt);
            }
        });
        getContentPane().add(btn_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, -1, -1));

        mouse_area.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                mouse_areaMouseDragged(evt);
            }
        });
        mouse_area.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mouse_areaMousePressed(evt);
            }
        });
        getContentPane().add(mouse_area, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 50));

        jPanel2.setBackground(new java.awt.Color(194, 206, 251));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_status.setFont(new java.awt.Font("Helvetica", 1, 12)); // NOI18N
        lbl_status.setText("Login Sebagai");
        jPanel2.add(lbl_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, -1));

        label_apaan.setFont(new java.awt.Font("Helvetica", 1, 11)); // NOI18N
        label_apaan.setText("Apaaan");
        jPanel2.add(label_apaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 70, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_registrasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menustuff/circle_registrasi.png"))); // NOI18N
        btn_registrasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_registrasiMouseClicked(evt);
            }
        });
        jPanel1.add(btn_registrasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 110, 110));

        btn_koceng.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menustuff/circle_koceng.png"))); // NOI18N
        btn_koceng.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_kocengMouseClicked(evt);
            }
        });
        jPanel1.add(btn_koceng, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 100, 110));

        btn_reservasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reserstuff/circle_reservasi1.png"))); // NOI18N
        btn_reservasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_reservasiMouseClicked(evt);
            }
        });
        jPanel1.add(btn_reservasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 112, 117));

        jLabel8.setFont(new java.awt.Font("Rubik", 1, 14)); // NOI18N
        jLabel8.setText("Reservasi");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, -1, -1));

        btn_bayar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reserstuff/circle_pembayaran.png"))); // NOI18N
        btn_bayar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_bayarMouseClicked(evt);
            }
        });
        jPanel1.add(btn_bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 100, 110));

        jLabel9.setFont(new java.awt.Font("Rubik", 1, 14)); // NOI18N
        jLabel9.setText("Pembayaran");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, -1, -1));

        jLabel1.setFont(new java.awt.Font("Rubik", 1, 14)); // NOI18N
        jLabel1.setText("Data Pemilik");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel2.setFont(new java.awt.Font("Rubik", 1, 14)); // NOI18N
        jLabel2.setText("Data Kucing");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, -1));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 142, 621, 220));

        jPanel3.setBackground(new java.awt.Color(98, 147, 245));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Helvetica", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Registrasi ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel4)
                .addContainerGap(537, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel4)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 200));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 460));

        setBounds(0, 0, 704, 455);
    }// </editor-fold>//GEN-END:initComponents

    private void mouse_areaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouse_areaMouseDragged
        // TODO add your handling code here:
        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        
        this.setLocation(xx-x, yy-y);
    }//GEN-LAST:event_mouse_areaMouseDragged

    private void mouse_areaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouse_areaMousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_mouse_areaMousePressed

    private void btn_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btn_closeMouseClicked

    private void btn_reservasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_reservasiMouseClicked
        // TODO add your handling code here:
        reservasi reser = new reservasi();
        reser.setVisible(true);
        reser.txt_idkar.setText(label_apaan.getText());
    }//GEN-LAST:event_btn_reservasiMouseClicked

    private void btn_bayarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_bayarMouseClicked
        // TODO add your handling code here:
        pembayaran bayar = new pembayaran();
        bayar.setVisible(true);
        bayar.txt_idkar.setText(label_apaan.getText());
    }//GEN-LAST:event_btn_bayarMouseClicked

    private void btn_registrasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registrasiMouseClicked
        // TODO add your handling code here:
        registrasi regs = new registrasi();
        regs.setVisible(true);        
    }//GEN-LAST:event_btn_registrasiMouseClicked

    private void btn_kocengMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_kocengMouseClicked
        // TODO add your handling code here:
        koceng cat = new koceng();
        cat.setVisible(true);        
    }//GEN-LAST:event_btn_kocengMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(regs_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(regs_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(regs_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(regs_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new regs_menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_bayar;
    private javax.swing.JLabel btn_close;
    private javax.swing.JLabel btn_koceng;
    private javax.swing.JLabel btn_registrasi;
    private javax.swing.JLabel btn_reservasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JLabel label_apaan;
    public javax.swing.JLabel lbl_status;
    private javax.swing.JLabel mouse_area;
    // End of variables declaration//GEN-END:variables
}
